#!/bin/csh
#==================================================================
#PBS -N JOB_NAME
#PBS -A PROJ_NUMBER
#PBS -j oe
#PBS -q main
#PBS -l select=NODES:ncpus=NCPUS:mpiprocs=NPROC:mem=230GB
#PBS -l job_priority=QUEUE
#PBS -l walltime=JOB_TIME
############################################
if(! -e logs) mkdir logs
set jobnum = `qstat | grep JOB_NAME | awk '{print $1}' | cut -d . -f1`
set logfile = JOB_NAME.o${jobnum}
echo $logfile

set myname = $0     # this is the name of this script
set start_time = `date +%s`
echo "host is " `hostname`

if ( -e filter_done ) \rm -f filter_done

# module purge
module load ncarenv/24.12 craype/2.7.31 intel/2024.2.1 ncarcompilers/1.0.0 cray-mpich/8.1.29 netcdf/4.9.2 
#module load peak-memusage

setenv OMP_NUM_THREADS 1
setenv MKL_NUM_THREADS 1
setenv OPENBLAS_NUM_THREADS 1
setenv MPICH_MEMORY_REPORT 0

echo $start_time >&! filter_started

# Launch one rank per member
mpiexec ./filter
#mpiexec peak_memusage ./filter
#mpiexec -n $(( NODES*NPROC )) ./filter     
wait

if ( -e obs_seq.final )  touch filter_done

set end_time = `date  +%s`
@ length_time = $end_time - $start_time
echo "duration_secs = $length_time"
